name: WordPress and PHP Matrix Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        wordpress_version: [6.4, 6.3, 6.2, 6.1]
        php_version: [8.3, 8.2, 8.1, 8.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MySQL
        run: sudo apt-get update && sudo apt-get install mysql-server -y

      - name: Start MySQL
        run: sudo service mysql start

      - name: Set up PHP and WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mbstring, zip, intl

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Set up WordPress
        run: |
          wget -O wordpress.tar.gz https://wordpress.org/latest.tar.gz
          tar -xzvf wordpress.tar.gz
          mv wordpress/* .

          wp plugin install woocommerce --activate

